# -*- coding: utf-8 -*-
"""Копия блокнота "Добро пожаловать в Colab!"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKHckA3yI94Exa90zFYhg-WrqxvX0kwl
"""

import numpy as np

import pandas as pd

import sklearn

import matplotlib.pyplot as plt #vizualizatsiya uchun

import seaborn as sns

import torch #deep learning uchun

import tensorflow as tf

import keras

tf.__version__

np.__version__

pd.__version__

import torch

torch.cuda.is_available()

! ls

"""data Komp_kriminal.xlsx sample_data"""

import pandas as pd

data = {
    "Ism": ["Jasur", "Ozod", "Subxon", "Odina"],
    "Yosh": [25, 40, 19, 28],
    "Maosh": [3000, 5000, 4500, 3200],
    "Bo'lim": ["IT", "HR", "IT", "Finance"]
}

df = pd.DataFrame(data)

df.to_excel("Komp_kriminal.xlsx", index=False)

print("Excel fayl yaratildi ✅")

import pandas as pd

files = pd.read_excel('Komp_kriminal.xlsx')

files.head()